//
//  ConfirmAddressInteractor.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfirmAddressBusinessLogic
{
  func doSomething(request: ConfirmAddress.Something.Request)
}

protocol ConfirmAddressDataStore
{
  //var name: String { get set }
}

class ConfirmAddressInteractor: ConfirmAddressBusinessLogic, ConfirmAddressDataStore
{
  var presenter: ConfirmAddressPresentationLogic?
  var worker: ConfirmAddressWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ConfirmAddress.Something.Request)
  {
    worker = ConfirmAddressWorker()
    worker?.doSomeWork()
    
    let response = ConfirmAddress.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
