//
//  ConfirmAddressPresenter.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfirmAddressPresentationLogic
{
  func presentSomething(response: ConfirmAddress.Something.Response)
}

class ConfirmAddressPresenter: ConfirmAddressPresentationLogic
{
  weak var viewController: ConfirmAddressDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ConfirmAddress.Something.Response)
  {
    let viewModel = ConfirmAddress.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
