//
//  ScheduleDeliveryInteractor.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScheduleDeliveryBusinessLogic
{
  func doSomething(request: ScheduleDelivery.Something.Request)
}

protocol ScheduleDeliveryDataStore
{
  //var name: String { get set }
}

class ScheduleDeliveryInteractor: ScheduleDeliveryBusinessLogic, ScheduleDeliveryDataStore
{
  var presenter: ScheduleDeliveryPresentationLogic?
  var worker: ScheduleDeliveryWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ScheduleDelivery.Something.Request)
  {
    worker = ScheduleDeliveryWorker()
    worker?.doSomeWork()
    
    let response = ScheduleDelivery.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
