//
//  WineInteractor.swift
//  VYNGLE
//
//  Created by Sujeet on 8/21/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WineBusinessLogic
{
  func doSomething(_ request: Wine.Something.Request)
}

protocol WineDataStore
{
  //var name: String { get set }
}

class WineInteractor: WineBusinessLogic, WineDataStore
{
  var presenter: WinePresentationLogic?
  var worker: WineWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(_ request: Wine.Something.Request)
  {
    worker = WineWorker()
    worker?.doSomeWork()
    
    let response = Wine.Something.Response()
    presenter?.presentSomething(response)
  }
}
