//
//  PaymentDetailsInteractor.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentDetailsBusinessLogic
{
  func doSomething(request: PaymentDetails.Something.Request)
}

protocol PaymentDetailsDataStore
{
  //var name: String { get set }
}

class PaymentDetailsInteractor: PaymentDetailsBusinessLogic, PaymentDetailsDataStore
{
  var presenter: PaymentDetailsPresentationLogic?
  var worker: PaymentDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PaymentDetails.Something.Request)
  {
    worker = PaymentDetailsWorker()
    worker?.doSomeWork()
    
    let response = PaymentDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
