//
//  PaymentDetailsPresenter.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentDetailsPresentationLogic
{
  func presentSomething(response: PaymentDetails.Something.Response)
}

class PaymentDetailsPresenter: PaymentDetailsPresentationLogic
{
  weak var viewController: PaymentDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PaymentDetails.Something.Response)
  {
    let viewModel = PaymentDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
