//
//  ReviewOrderViewController.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewOrderDisplayLogic: class
{
  func displaySomething(viewModel: ReviewOrder.Something.ViewModel)
}

class ReviewOrderViewController: UIViewController, ReviewOrderDisplayLogic
{
  var interactor: ReviewOrderBusinessLogic?
  var router: (NSObjectProtocol & ReviewOrderRoutingLogic & ReviewOrderDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ReviewOrderInteractor()
    let presenter = ReviewOrderPresenter()
    let router = ReviewOrderRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = ReviewOrder.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ReviewOrder.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
