//
//  ReviewOrderPresenter.swift
//  VYNGLE
//
//  Created by Sujeet on 8/27/17.
//  Copyright (c) 2017 Sujeet. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewOrderPresentationLogic
{
  func presentSomething(response: ReviewOrder.Something.Response)
}

class ReviewOrderPresenter: ReviewOrderPresentationLogic
{
  weak var viewController: ReviewOrderDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ReviewOrder.Something.Response)
  {
    let viewModel = ReviewOrder.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
